// Code generated by internal/gen from index.xml; DO NOT EDIT.

package schema

import "strconv"

// ColumnType is the GDPdU data type of a column, as declared in index.xml.
type ColumnType uint8

const (
	ColumnAlphaNumeric ColumnType = iota
	ColumnNumeric
)

// String returns the GDPdU element name of the type.
func (t ColumnType) String() string {
	switch t {
	case ColumnAlphaNumeric:
		return "AlphaNumeric"
	case ColumnNumeric:
		return "Numeric"
	default:
		return "ColumnType(" + strconv.Itoa(int(t)) + ")"
	}
}

// Column is one <VariableColumn> of a DSFinV-K table.
type Column struct {
	Name        string
	Description string
	Type        ColumnType
	MaxLength   int
	Accuracy    int
}

// Table is one <Table> of a DSFinV-K export.
type Table struct {
	File        string
	Name        string
	Description string
	Columns     []Column
}

// CSV dialect of every DSFinV-K table, read from index.xml.
const (
	ColumnDelimiter  = ';'
	TextEncapsulator = '"'
	RecordDelimiter  = "\r\n"
	DecimalSymbol    = ','
	// DigitGroupingSymbol is what index.xml declares; grouping must not be emitted.
	DigitGroupingSymbol = '.'
	Encoding            = "UTF-8"
	HeaderRow           = 1
	DataStartRow        = 2
)

// tables are the DSFinV-K tables in index.xml order; Tables clones them.
var tables = []Table{
	{
		File:        "cashpointclosing.csv",
		Name:        "Stamm_Abschluss",
		Description: "cashpointclosing.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "Z_BUCHUNGSTAG", Description: "Vom Erstellungsdatum abweichender Verbuchungstag", Type: ColumnAlphaNumeric, MaxLength: 25},
			{Name: "TAXONOMIE_VERSION", Description: "Version der DFKA-Taxonomie-Kasse", Type: ColumnAlphaNumeric, MaxLength: 10},
			{Name: "Z_START_ID", Description: "Erste BON_ID im Abschluss", Type: ColumnAlphaNumeric, MaxLength: 40},
			{Name: "Z_ENDE_ID", Description: "Letzte BON_ID im Abschluss", Type: ColumnAlphaNumeric, MaxLength: 40},
			{Name: "NAME", Description: "Name des Unternehmens", Type: ColumnAlphaNumeric, MaxLength: 60},
			{Name: "STRASSE", Description: "Straße", Type: ColumnAlphaNumeric, MaxLength: 60},
			{Name: "PLZ", Description: "Postleitzahl", Type: ColumnAlphaNumeric, MaxLength: 10},
			{Name: "ORT", Description: "Ort", Type: ColumnAlphaNumeric, MaxLength: 62},
			{Name: "LAND", Description: "Land", Type: ColumnAlphaNumeric, MaxLength: 3},
			{Name: "STNR", Description: "Steuernummer des Unternehmens", Type: ColumnAlphaNumeric, MaxLength: 20},
			{Name: "USTID", Description: "USTID", Type: ColumnAlphaNumeric, MaxLength: 15},
			{Name: "Z_SE_ZAHLUNGEN", Description: "Summe aller Zahlungen", Type: ColumnNumeric, Accuracy: 2},
			{Name: "Z_SE_BARZAHLUNGEN", Description: "Summe aller Barzahlungen", Type: ColumnNumeric, Accuracy: 2},
		},
	},
	{
		File:        "location.csv",
		Name:        "Stamm_Orte",
		Description: "location.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "LOC_NAME", Description: "Name des Standortes", Type: ColumnAlphaNumeric, MaxLength: 60},
			{Name: "LOC_STRASSE", Description: "Straße", Type: ColumnAlphaNumeric, MaxLength: 60},
			{Name: "LOC_PLZ", Description: "Postleitzahl", Type: ColumnAlphaNumeric, MaxLength: 10},
			{Name: "LOC_ORT", Description: "Ort", Type: ColumnAlphaNumeric, MaxLength: 62},
			{Name: "LOC_LAND", Description: "Land", Type: ColumnAlphaNumeric, MaxLength: 3},
			{Name: "LOC_USTID", Description: "USTID", Type: ColumnAlphaNumeric, MaxLength: 15},
		},
	},
	{
		File:        "cashregister.csv",
		Name:        "Stamm_Kassen",
		Description: "cashregister.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "KASSE_BRAND", Description: "Marke der Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "KASSE_MODELL", Description: "Modellbezeichnung", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "KASSE_SERIENNR", Description: "Seriennummer der Kasse", Type: ColumnAlphaNumeric, MaxLength: 70},
			{Name: "KASSE_SW_BRAND", Description: "Markenbezeichnung der Software", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "KASSE_SW_VERSION", Description: "Version der Software", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "KASSE_BASISWAEH_CODE", Description: "Basiswährung der Kasse", Type: ColumnAlphaNumeric, MaxLength: 3},
			{Name: "KEINE_UST_ZUORDNUNG", Description: "UmsatzsteuerNichtErmittelbar (bei späterem Zahlungseingang)", Type: ColumnAlphaNumeric, MaxLength: 1},
		},
	},
	{
		File:        "slaves.csv",
		Name:        "Stamm_Terminals",
		Description: "slaves.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "TERMINAL_ID", Description: "ID des Terminals", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "TERMINAL_BRAND", Description: "Marke der Terminals", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "TERMINAL_MODELL", Description: "Modellbezeichnung des Terminals", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "TERMINAL_SERIENNR", Description: "Seriennummer des Terminals", Type: ColumnAlphaNumeric, MaxLength: 70},
			{Name: "TERMINAL_SW_BRAND", Description: "Markenbezeichnung der Software", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "TERMINAL_SW_VERSION", Description: "Version der Software", Type: ColumnAlphaNumeric, MaxLength: 50},
		},
	},
	{
		File:        "pa.csv",
		Name:        "Stamm_Agenturen",
		Description: "pa.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "AGENTUR_ID", Description: "ID der Agentur", Type: ColumnNumeric},
			{Name: "AGENTUR_NAME", Description: "Name des Auftraggebers", Type: ColumnAlphaNumeric, MaxLength: 60},
			{Name: "AGENTUR_STRASSE", Description: "Straße", Type: ColumnAlphaNumeric, MaxLength: 60},
			{Name: "AGENTUR_PLZ", Description: "Postleitzahl", Type: ColumnAlphaNumeric, MaxLength: 10},
			{Name: "AGENTUR_ORT", Description: "Ort", Type: ColumnAlphaNumeric, MaxLength: 62},
			{Name: "AGENTUR_LAND", Description: "Land", Type: ColumnAlphaNumeric, MaxLength: 3},
			{Name: "AGENTUR_STNR", Description: "Steuernummer des Auftraggebers", Type: ColumnAlphaNumeric, MaxLength: 20},
			{Name: "AGENTUR_USTID", Description: "USTID des Auftraggebers", Type: ColumnAlphaNumeric, MaxLength: 15},
		},
	},
	{
		File:        "tse.csv",
		Name:        "Stamm_TSE",
		Description: "tse.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "TSE_ID", Description: "ID der TSE - wird nur zur Referenzierung innerhalb eines Kassenabschlusses verwendet", Type: ColumnNumeric},
			{Name: "TSE_SERIAL", Description: "Seriennummer der TSE (Entspricht laut TR-03153 Abschnitt 7.5. dem Hashwert des im Zertifikat enthaltenen Schlüssels in Octet-String-Darstellung)", Type: ColumnAlphaNumeric, MaxLength: 68},
			{Name: "TSE_SIG_ALGO", Description: "Der von der TSE verwendete Signaturalgo-rithmus", Type: ColumnAlphaNumeric, MaxLength: 21},
			{Name: "TSE_ZEITFORMAT", Description: "Das von der TSE verwendete Format für die Log-Time - 'unixTime', 'utcTime' = YYMMDDhhmmZ, 'utcTimeWithSeconds' = YYMMDDhhmmssZ, 'generalizedTime' = YYYYMMDDhhmmssZ, 'generalizedTimeWithMilliseconds' = YYYYMMDDhhmmss.fffZ", Type: ColumnAlphaNumeric, MaxLength: 31},
			{Name: "TSE_PD_ENCODING", Description: "Das Text-Encoding der ProcessData (UTF-8 oder ASCII)", Type: ColumnAlphaNumeric, MaxLength: 5},
			{Name: "TSE_PUBLIC_KEY", Description: "Öffentlicher Schlüssel - extrahiert aus dem Zertifikat der TSE - in base64-Codierung", Type: ColumnAlphaNumeric, MaxLength: 512},
			{Name: "TSE_ZERTIFIKAT_I", Description: "Erste 1000 Zeichen des base64-codierten Zertifikats der TSE (in base64-Codierung)", Type: ColumnAlphaNumeric, MaxLength: 1000},
			{Name: "TSE_ZERTIFIKAT_II", Description: "Ggf. Rest des base64-codierten Zertifikats der TSE (in base64-Codierung)", Type: ColumnAlphaNumeric, MaxLength: 1000},
		},
	},
	{
		File:        "vat.csv",
		Name:        "Stamm_USt",
		Description: "vat.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "UST_SCHLUESSEL", Description: "ID des Umsatzsteuersatzes", Type: ColumnNumeric},
			{Name: "UST_SATZ", Description: "Prozentsatz", Type: ColumnNumeric, Accuracy: 2},
			{Name: "UST_BESCHR", Description: "Beschreibung", Type: ColumnAlphaNumeric, MaxLength: 55},
		},
	},
	{
		File:        "businesscases.csv",
		Name:        "Z_GV_Typ",
		Description: "businesscases.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "GV_TYP", Description: "Geschäftsvorfall-Art", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "GV_NAME", Description: "Name des Geschäftsvorfalls", Type: ColumnAlphaNumeric, MaxLength: 40},
			{Name: "AGENTUR_ID", Description: "ID der Agentur", Type: ColumnNumeric},
			{Name: "UST_SCHLUESSEL", Description: "ID des USt-Satzes", Type: ColumnNumeric},
			{Name: "Z_UMS_BRUTTO", Description: "Bruttoumsatz", Type: ColumnNumeric, Accuracy: 5},
			{Name: "Z_UMS_NETTO", Description: "Nettoumsatz", Type: ColumnNumeric, Accuracy: 5},
			{Name: "Z_UST", Description: "Umsatzsteuer", Type: ColumnNumeric, Accuracy: 5},
		},
	},
	{
		File:        "payment.csv",
		Name:        "Z_Zahlart",
		Description: "payment.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "ZAHLART_TYP", Description: "Typ der Zahlart", Type: ColumnAlphaNumeric, MaxLength: 25},
			{Name: "ZAHLART_NAME", Description: "Name der Zahlart", Type: ColumnAlphaNumeric, MaxLength: 60},
			{Name: "Z_ZAHLART_BETRAG", Description: "Betrag", Type: ColumnNumeric, Accuracy: 2},
		},
	},
	{
		File:        "cash_per_currency.csv",
		Name:        "Z_Waehrungen",
		Description: "cash_per_currency.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "ZAHLART_WAEH", Description: "Währung", Type: ColumnAlphaNumeric, MaxLength: 3},
			{Name: "ZAHLART_BETRAG_WAEH", Description: "Betrag", Type: ColumnNumeric, Accuracy: 2},
		},
	},
	{
		File:        "transactions.csv",
		Name:        "Bonkopf",
		Description: "transactions.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "BON_ID", Description: "Vorgangs-ID", Type: ColumnAlphaNumeric, MaxLength: 40},
			{Name: "BON_NR", Description: "Bonnummer", Type: ColumnNumeric},
			{Name: "BON_TYP", Description: "Bontyp", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "BON_NAME", Description: "Zusatz-Beschreibung zum Bontyp", Type: ColumnAlphaNumeric, MaxLength: 60},
			{Name: "TERMINAL_ID", Description: "ID des Erfassungsterminals", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "BON_STORNO", Description: "Storno-Kennzeichen", Type: ColumnAlphaNumeric, MaxLength: 1},
			{Name: "BON_START", Description: "Zeitpunkt des Vorgangsstarts", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "BON_ENDE", Description: "Zeitpunkt der Vorgangsbeendigung", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "BEDIENER_ID", Description: "Bediener-ID", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "BEDIENER_NAME", Description: "Bediener-Name", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "UMS_BRUTTO", Description: "Brutto-Gesamtumsatz", Type: ColumnNumeric, Accuracy: 2},
			{Name: "KUNDE_NAME", Description: "Name des Leistungsempfängers", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "KUNDE_ID", Description: "Kundennummer des Leistungsempfängers", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "KUNDE_TYP", Description: "Art des Leistungsempfängers (z. B. Mitarbeiter)", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "KUNDE_STRASSE", Description: "Straße und Hausnummer des Leistungsempfängers", Type: ColumnAlphaNumeric, MaxLength: 60},
			{Name: "KUNDE_PLZ", Description: "PLZ des Leistungsempfängers", Type: ColumnAlphaNumeric, MaxLength: 10},
			{Name: "KUNDE_ORT", Description: "Ort des Leistungsempfängers", Type: ColumnAlphaNumeric, MaxLength: 62},
			{Name: "KUNDE_LAND", Description: "Land des Leistungsempfängers", Type: ColumnAlphaNumeric, MaxLength: 3},
			{Name: "KUNDE_USTID", Description: "UStID des Leistungsempfängers", Type: ColumnAlphaNumeric, MaxLength: 15},
			{Name: "BON_NOTIZ", Description: "Zusätzliche Informationen zum Bonkopf", Type: ColumnAlphaNumeric, MaxLength: 255},
		},
	},
	{
		File:        "datapayment.csv",
		Name:        "Bonkopf_Zahlarten",
		Description: "datapayment.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "BON_ID", Description: "Vorgangs-ID", Type: ColumnAlphaNumeric, MaxLength: 40},
			{Name: "ZAHLART_TYP", Description: "Typ der Zahlart", Type: ColumnAlphaNumeric, MaxLength: 25},
			{Name: "ZAHLART_NAME", Description: "Name der Zahlart", Type: ColumnAlphaNumeric, MaxLength: 60},
			{Name: "ZAHLWAEH_CODE", Description: "Währungscode", Type: ColumnAlphaNumeric, MaxLength: 3},
			{Name: "ZAHLWAEH_BETRAG", Description: "Betrag in Fremdwährung", Type: ColumnNumeric, Accuracy: 2},
			{Name: "BASISWAEH_BETRAG", Description: "Betrag in Basiswährung (i.d.R. EUR)", Type: ColumnNumeric, Accuracy: 2},
		},
	},
	{
		File:        "lines.csv",
		Name:        "Bonpos",
		Description: "lines.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "BON_ID", Description: "Vorgangs-ID", Type: ColumnAlphaNumeric, MaxLength: 40},
			{Name: "POS_ZEILE", Description: "Zeilennummer", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "GUTSCHEIN_NR", Description: "Gutschein-Nr.", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "ARTIKELTEXT", Description: "Artikeltext", Type: ColumnAlphaNumeric, MaxLength: 255},
			{Name: "POS_TERMINAL_ID", Description: "ID des POS-Terminals", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "GV_TYP", Description: "Geschäftsvorfall-Art", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "GV_NAME", Description: "Name des Geschäftsvorfalls", Type: ColumnAlphaNumeric, MaxLength: 40},
			{Name: "INHAUS", Description: "Verzehr an Ort und Stelle", Type: ColumnAlphaNumeric, MaxLength: 1},
			{Name: "P_STORNO", Description: "Positionsstorno-Kennzeichnung", Type: ColumnAlphaNumeric, MaxLength: 1},
			{Name: "AGENTUR_ID", Description: "ID der Agentur", Type: ColumnNumeric},
			{Name: "ART_NR", Description: "Artikelnummer", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "GTIN", Description: "GTIN", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "WARENGR_ID", Description: "Warengruppen-ID", Type: ColumnAlphaNumeric, MaxLength: 40},
			{Name: "WARENGR", Description: "Bezeichnung Warengruppe", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "MENGE", Description: "Menge", Type: ColumnNumeric, Accuracy: 3},
			{Name: "FAKTOR", Description: "Faktor, z. B. Gebindegrößen", Type: ColumnNumeric, Accuracy: 3},
			{Name: "EINHEIT", Description: "Maßeinheit, z. B. kg, Liter oder Stück", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "STK_BR", Description: "Preis pro Einheit inkl. USt", Type: ColumnNumeric, Accuracy: 5},
		},
	},
	{
		File:        "itemamounts.csv",
		Name:        "Bonpos_Preisfindung",
		Description: "itemamounts.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "BON_ID", Description: "Vorgangs-ID", Type: ColumnAlphaNumeric, MaxLength: 40},
			{Name: "POS_ZEILE", Description: "Zeilennummer", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "TYP", Description: "Basispreis, Rabatt oder Zuschlag", Type: ColumnAlphaNumeric, MaxLength: 20},
			{Name: "UST_SCHLUESSEL", Description: "ID des USt-Satzes", Type: ColumnNumeric},
			{Name: "PF_BRUTTO", Description: "Bruttoumsatz", Type: ColumnNumeric, Accuracy: 5},
			{Name: "PF_NETTO", Description: "Nettoumsatz", Type: ColumnNumeric, Accuracy: 5},
			{Name: "PF_UST", Description: "Umsatzsteuer", Type: ColumnNumeric, Accuracy: 5},
		},
	},
	{
		File:        "subitems.csv",
		Name:        "Bonpos_Zusatzinfo",
		Description: "subitems.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "BON_ID", Description: "Vorgangs-ID", Type: ColumnAlphaNumeric, MaxLength: 40},
			{Name: "POS_ZEILE", Description: "Zeilennummer", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "ZI_ART_NR", Description: "Artikelnummer", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "ZI_GTIN", Description: "GTIN", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "ZI_NAME", Description: "Artikelbezeichnung", Type: ColumnAlphaNumeric, MaxLength: 60},
			{Name: "ZI_WARENGR_ID", Description: "Warengruppen-ID", Type: ColumnAlphaNumeric, MaxLength: 40},
			{Name: "ZI_WARENGR", Description: "Bezeichnung Warengruppe", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "ZI_MENGE", Description: "Menge", Type: ColumnNumeric, Accuracy: 3},
			{Name: "ZI_FAKTOR", Description: "Faktor, z. B. Gebindegrößen", Type: ColumnNumeric, Accuracy: 3},
			{Name: "ZI_EINHEIT", Description: "Maßeinheit, z. B. kg, Liter oder Stück", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "ZI_UST_SCHLUESSEL", Description: "ID USt-Satz des Basispreises", Type: ColumnNumeric},
			{Name: "ZI_BASISPREIS_BRUTTO", Description: "Basispreis brutto", Type: ColumnNumeric, Accuracy: 5},
			{Name: "ZI_BASISPREIS_NETTO", Description: "Basispreis netto", Type: ColumnNumeric, Accuracy: 5},
			{Name: "ZI_BASISPREIS_UST", Description: "Basispreis USt", Type: ColumnNumeric, Accuracy: 5},
		},
	},
	{
		File:        "transactions_tse.csv",
		Name:        "TSE_Transaktionen",
		Description: "transactions_tse.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "BON_ID", Description: "Vorgangs-ID", Type: ColumnAlphaNumeric, MaxLength: 40},
			{Name: "TSE_ID", Description: "Die Id der für eine Transaktion verwendeten TSE", Type: ColumnNumeric},
			{Name: "TSE_TANR", Description: "Die Transaktionsnummer der TSE-Transaktion", Type: ColumnNumeric},
			{Name: "TSE_TA_START", Description: "Die Log-Time der StartTransaction-Operation", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "TSE_TA_ENDE", Description: "Die Log-Time der FinishTransaction-Operation", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "TSE_TA_VORGANGSART", Description: "Der processType der FinishTransaction-Operation", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "TSE_TA_SIGZ", Description: "Der Signaturzähler der FinishTransaction-Operation", Type: ColumnNumeric},
			{Name: "TSE_TA_SIG", Description: "Die Signatur der FinishTransaction-Operation", Type: ColumnAlphaNumeric, MaxLength: 512},
			{Name: "TSE_TA_FEHLER", Description: "Beschreibung des TSE-Ausfalls oder Fehlers", Type: ColumnAlphaNumeric, MaxLength: 200},
			{Name: "TSE_VORGANGSDATEN", Description: "An die zertifizierte technische Sicherheitseinrichtung übergebene Daten des Vorgangs (optional)", Type: ColumnAlphaNumeric, MaxLength: 1000},
		},
	},
	{
		File:        "transactions_vat.csv",
		Name:        "Bonkopf_USt",
		Description: "transactions_vat.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "BON_ID", Description: "Vorgangs-ID", Type: ColumnAlphaNumeric, MaxLength: 40},
			{Name: "UST_SCHLUESSEL", Description: "ID des USt-Satzes", Type: ColumnNumeric},
			{Name: "BON_BRUTTO", Description: "Bruttoumsatz", Type: ColumnNumeric, Accuracy: 5},
			{Name: "BON_NETTO", Description: "Nettoumsatz", Type: ColumnNumeric, Accuracy: 5},
			{Name: "BON_UST", Description: "Umsatzsteuer", Type: ColumnNumeric, Accuracy: 5},
		},
	},
	{
		File:        "lines_vat.csv",
		Name:        "Bonpos_USt",
		Description: "lines_vat.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "BON_ID", Description: "Vorgangs-ID", Type: ColumnAlphaNumeric, MaxLength: 40},
			{Name: "POS_ZEILE", Description: "Zeilennummer", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "UST_SCHLUESSEL", Description: "ID des USt-Satzes", Type: ColumnNumeric},
			{Name: "POS_BRUTTO", Description: "Bruttoumsatz", Type: ColumnNumeric, Accuracy: 5},
			{Name: "POS_NETTO", Description: "Nettoumsatz", Type: ColumnNumeric, Accuracy: 5},
			{Name: "POS_UST", Description: "Umsatzsteuer", Type: ColumnNumeric, Accuracy: 5},
		},
	},
	{
		File:        "allocation_groups.csv",
		Name:        "Bonkopf_AbrKreis",
		Description: "allocation_groups.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "BON_ID", Description: "Vorgangs-ID", Type: ColumnAlphaNumeric, MaxLength: 40},
			{Name: "ABRECHNUNGSKREIS", Description: "z. B. Tischnummer", Type: ColumnAlphaNumeric, MaxLength: 50},
		},
	},
	{
		File:        "references.csv",
		Name:        "Bon_Referenzen",
		Description: "references.csv",
		Columns: []Column{
			{Name: "Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "Z_ERSTELLUNG", Description: "Zeitpunkt des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "BON_ID", Description: "Vorgangs-ID", Type: ColumnAlphaNumeric, MaxLength: 40},
			{Name: "POS_ZEILE", Description: "Zeilennummer des referenzierenden Vorgangs (nicht bei Verweis aus einem Bonkopf heraus)", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "REF_TYP", Description: "Art der Referenz", Type: ColumnAlphaNumeric, MaxLength: 20},
			{Name: "REF_NAME", Description: "Beschreibung bei Art “ExterneSonstige”", Type: ColumnAlphaNumeric, MaxLength: 40},
			{Name: "REF_DATUM", Description: "Datum des Kassenabschlusses", Type: ColumnAlphaNumeric, MaxLength: 30},
			{Name: "REF_Z_KASSE_ID", Description: "ID der (Abschluss-) Kasse", Type: ColumnAlphaNumeric, MaxLength: 50},
			{Name: "REF_Z_NR", Description: "Nr. des Kassenabschlusses", Type: ColumnNumeric},
			{Name: "REF_BON_ID", Description: "Vorgangs-ID", Type: ColumnAlphaNumeric, MaxLength: 40},
		},
	},
}
